# Generated by Django 3.1 on 2020-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remaining',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
